// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFfTBwF-HXWATxcknSaxguozhsxzNLYJA',
    appId: '1:654932840054:web:d26424cbc61de08d89d957',
    messagingSenderId: '654932840054',
    projectId: 'swap-e9630',
    authDomain: 'swap-e9630.firebaseapp.com',
    storageBucket: 'swap-e9630.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevP47EVaXhBnax9v110pjToNTR4XuQa0',
    appId: '1:654932840054:android:8981cc54a7875a5b89d957',
    messagingSenderId: '654932840054',
    projectId: 'swap-e9630',
    storageBucket: 'swap-e9630.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAevP47EVaXhBnax9v110pjToNTR4XuQa0',
    appId: '1:654932840054:ios:8981cc54a7875a5b89d957',
    messagingSenderId: '654932840054',
    projectId: 'swap-e9630',
    storageBucket: 'swap-e9630.firebasestorage.app',
    iosBundleId: 'com.example.freeobminFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAevP47EVaXhBnax9v110pjToNTR4XuQa0',
    appId: '1:654932840054:ios:8981cc54a7875a5b89d957',
    messagingSenderId: '654932840054',
    projectId: 'swap-e9630',
    storageBucket: 'swap-e9630.firebasestorage.app',
    iosBundleId: 'com.example.freeobminFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAevP47EVaXhBnax9v110pjToNTR4XuQa0',
    appId: '1:654932840054:web:d26424cbc61de08d89d957',
    messagingSenderId: '654932840054',
    projectId: 'swap-e9630',
    authDomain: 'swap-e9630.firebaseapp.com',
    storageBucket: 'swap-e9630.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAevP47EVaXhBnax9v110pjToNTR4XuQa0',
    appId: '1:654932840054:web:d26424cbc61de08d89d957',
    messagingSenderId: '654932840054',
    projectId: 'swap-e9630',
    authDomain: 'swap-e9630.firebaseapp.com',
    storageBucket: 'swap-e9630.appspot.com',
  );
}
